<?php
require_once __DIR__ . '/includes/auth.php'; require_login();
$userId = (int) $_SESSION['user_id']; archive_completed_years($pdo, $userId);
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); [$errors, $data] = validate_transaction($_POST);
    if (!$errors) { $statement = $pdo->prepare('INSERT INTO transactions (user_id, type, amount, transaction_date, note) VALUES (:user_id, :type, :amount, :transaction_date, :note)'); $statement->execute(['user_id'=>$userId, 'type'=>$data['type'], 'amount'=>$data['amount'], 'transaction_date'=>$data['transaction_date'], 'note'=>$data['note'] ?: null]); flash('success', 'Transaction saved successfully.'); redirect('dashboard.php'); }
    foreach ($errors as $error) flash('error', $error); redirect('dashboard.php');
}
$today = new DateTimeImmutable('today'); $monthStart = $today->modify('first day of this month')->format('Y-m-d'); $nextMonth = $today->modify('first day of next month')->format('Y-m-d'); $previousStart = $today->modify('first day of previous month')->format('Y-m-d');
$current = period_totals($pdo, $userId, '1000-01-01', '9999-12-31'); $thisMonth = period_totals($pdo, $userId, $monthStart, $nextMonth); $previousMonth = period_totals($pdo, $userId, $previousStart, $monthStart); $last12 = period_totals($pdo, $userId, $today->modify('-11 months')->modify('first day of this month')->format('Y-m-d'), $nextMonth);
$type = $_GET['type'] ?? ''; $year = (int) ($_GET['year'] ?? 0); $month = (int) ($_GET['month'] ?? 0); $search = trim($_GET['search'] ?? '');
$sql = 'SELECT * FROM transactions WHERE user_id = :user_id'; $params = ['user_id'=>$userId]; if (in_array($type, ['Income','Expense'], true)) {$sql .= ' AND type = :type'; $params['type']=$type;} if ($year > 1900) {$sql .= ' AND YEAR(transaction_date) = :year'; $params['year']=$year;} if ($month >= 1 && $month <= 12) {$sql .= ' AND MONTH(transaction_date) = :month'; $params['month']=$month;} if ($search !== '') {$sql .= ' AND note LIKE :search'; $params['search']='%'.$search.'%';} $sql .= ' ORDER BY transaction_date DESC, id DESC LIMIT 100'; $statement=$pdo->prepare($sql); $statement->execute($params); $transactions=$statement->fetchAll();
$archiveStatement=$pdo->prepare('SELECT * FROM yearly_archive WHERE user_id = :user_id ORDER BY year DESC LIMIT 3'); $archiveStatement->execute(['user_id'=>$userId]); $archives=$archiveStatement->fetchAll();
$chartStatement=$pdo->prepare("SELECT DATE_FORMAT(transaction_date, '%b %Y') AS label, DATE_FORMAT(transaction_date, '%Y-%m') AS month_key, SUM(CASE WHEN type='Income' THEN amount ELSE 0 END) AS income, SUM(CASE WHEN type='Expense' THEN amount ELSE 0 END) AS expense FROM transactions WHERE user_id=:user_id AND transaction_date >= :from_date GROUP BY month_key, label ORDER BY month_key"); $chartStatement->execute(['user_id'=>$userId,'from_date'=>$today->modify('-11 months')->modify('first day of this month')->format('Y-m-d')]); $chartRows=$chartStatement->fetchAll(); $labels=array_column($chartRows,'label'); $incomes=array_map('floatval',array_column($chartRows,'income')); $expenses=array_map('floatval',array_column($chartRows,'expense'));
$pageTitle='Dashboard'; require __DIR__.'/includes/header.php';
?>
<div class="page-title"><div><span class="eyebrow">FINANCIAL OVERVIEW</span><h1>Dashboard</h1></div><span class="muted small">Updated <?= date('M d, Y') ?></span></div>
<section class="summary-grid"><article class="summary-card"><h3>Current Balance</h3><div class="summary-value green"><?= money($current['balance']) ?></div><p class="summary-detail">Income: <?= money($current['income']) ?></p><p class="summary-detail">Expense: <?= money($current['expense']) ?></p></article><article class="summary-card"><h3>This Month</h3><div class="summary-value blue"><?= money($thisMonth['balance']) ?></div><p class="summary-detail">Income: <?= money($thisMonth['income']) ?></p><p class="summary-detail">Expense: <?= money($thisMonth['expense']) ?></p></article><article class="summary-card"><h3>Previous Month</h3><div class="summary-value blue"><?= money($previousMonth['balance']) ?></div><p class="summary-detail">Income: <?= money($previousMonth['income']) ?></p><p class="summary-detail">Expense: <?= money($previousMonth['expense']) ?></p></article><article class="summary-card"><h3>Last 12 Months</h3><div class="summary-value green"><?= money($last12['balance']) ?></div><p class="summary-detail">Income: <?= money($last12['income']) ?></p><p class="summary-detail">Expense: <?= money($last12['expense']) ?></p></article></section>
<div class="dashboard-grid"><div><section class="panel"><div class="panel-title"><h2>Add New Transaction</h2><span class="muted small">Keep it current</span></div><form method="post" class="transaction-form"><input type="hidden" name="_csrf" value="<?= e(csrf_token()) ?>"><div><label>Type</label><select class="form-select" name="type"><option>Income</option><option>Expense</option></select></div><div><label>Amount</label><input class="form-control" type="number" name="amount" min="0.01" step="0.01" required></div><div><label>Date</label><input class="form-control" type="date" name="transaction_date" value="<?= date('Y-m-d') ?>" required></div><div><label>Note</label><input class="form-control" name="note" maxlength="255" placeholder="Optional"></div><button class="btn btn-primary"><i class="fa-solid fa-plus me-1"></i> Save</button></form></section><section class="panel chart-panel"><div class="panel-title"><h2>Income vs Expense</h2><a href="transactions.php" class="action-link">View all</a></div><canvas data-chart='<?= e(json_encode(['type'=>'bar','labels'=>$labels,'datasets'=>[['label'=>'Income','data'=>$incomes,'backgroundColor'=>'#159447'],['label'=>'Expense','data'=>$expenses,'backgroundColor'=>'#d94a5c']]])) ?>'></canvas></section></div><aside><section class="panel"><div class="panel-title"><h2>Yearly Savings Archive</h2><a href="archive.php" class="action-link">All</a></div><?php if (!$archives): ?><div class="empty-state">Your completed years will appear here.</div><?php else: ?><div class="archive-list"><?php foreach($archives as $archive): ?><div class="archive-item"><div><strong><?= e((string)$archive['year']) ?></strong><span>Saved balance</span></div><strong class="text-success"><?= money($archive['total_balance']) ?></strong></div><?php endforeach; ?></div><?php endif; ?></section></aside></div>
<section class="panel mt-4"><div class="panel-title"><h2>Recent Transactions</h2><a href="transactions.php" class="action-link">Manage transactions</a></div><?php if (!$transactions): ?><div class="empty-state">No transactions yet. Add your first one above.</div><?php else: ?><div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Date</th><th>Type</th><th>Amount</th><th>Note</th><th>Actions</th></tr></thead><tbody><?php foreach($transactions as $transaction): ?><tr><td>#<?= (int)$transaction['id'] ?></td><td><?= pretty_date($transaction['transaction_date']) ?></td><td><span class="badge rounded-pill <?= $transaction['type']==='Income'?'badge-income':'badge-expense' ?>"><?= e($transaction['type']) ?></span></td><td class="fw-semibold <?= $transaction['type']==='Income'?'text-success':'text-danger' ?>"><?= $transaction['type']==='Expense'?'- ':'' ?><?= money($transaction['amount']) ?></td><td><?= e($transaction['note'] ?: '—') ?></td><td><a class="action-link" href="edit_transaction.php?id=<?= (int)$transaction['id'] ?>">Edit</a><a class="action-link delete" data-confirm="Are you sure you want to delete this transaction?" href="delete_transaction.php?id=<?= (int)$transaction['id'] ?>&token=<?= e(csrf_token()) ?>">Delete</a></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php require __DIR__.'/includes/footer.php'; ?><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script><script src="assets/js/charts.js"></script>
